---
abstract: 'map VMethod for Template::Tookit'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Template::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Map
requires:
  Template: 2.0
  Template::Plugin::VMethods: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Map
  homepage: http://search.cpan.org/dist/Template-Plugin-Map/
  repository: git://github.com/mschout/template-plugin-map.git
version: 0.01
